import{a as u,S as d,i as a}from"./assets/vendor-BIQ21uCa.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const m="https://pixabay.com/api/",p="54227747-d3c13079e82325bc2c9b382ac";async function y(s){return(await u.get(m,{params:{key:p,q:s,image_type:"photo",orientation:"horizontal",satisfies:"true"}})).data}const c=document.querySelector(".gallery"),l=document.querySelector(".loader"),f=document.querySelector(".loader-text"),g=new d(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){const t=s.map(r=>`
        <li>
        <a href="${r.largeImageURL}"> 
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        <div class="info">
            <p><b>Likes:</b> ${r.likes}</p>
            <p><b>Views:</b> ${r.views}</p>
            <p><b>Comments:</b> ${r.comments}</p>
            <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
        </a>
        </li>`).join("");c.insertAdjacentHTML("beforeend",t),g.refresh()}function b(){c.innerHTML=""}function L(){l.classList.add("is-visible"),f.classList.add("is-visible")}function v(){l.classList.remove("is-visible"),f.classList.remove("is-visible")}const w=document.querySelector(".form");w.addEventListener("submit",S);async function S(s){s.preventDefault();const t=s.target.elements["search-text"].value.trim();if(!t){a.warning({message:"Please enter a search query.",position:"topRight"});return}b(),L();try{const r=await y(t);if(!r.hits.length){a.error({message:"Sorry, there are no images matching <br>yoursearch query. Please, try again!",position:"topRight",backgroundColor:"#e74c3c",messageColor:"#ffffff",iconColor:"#ffffff",icon:"ico-error",theme:"dark",close:!0,closeColor:"#ffffff"});return}h(r.hits.slice(0,9))}catch(r){a.error({message:"Sorry, there are no images matching <br>your search query. Please, try again!",position:"topRight",backgroundColor:"#e74c3c",messageColor:"#ffffff",iconColor:"#ffffff",icon:"ico-error",theme:"dark",close:!0,closeColor:"#ffffff"}),console.error("Error fetching images:",r)}finally{v()}}
//# sourceMappingURL=index.js.map
